- name: calling the vault
  hosts: localhost
  conection: local
  tasks:
    - name: calling the secret
      ansible.builtin.debug:
         msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=test2/data/demos-winsh:password token={{ vault-token }} url=http://52.224.245.194:8200/') }}"