- name: condition
  hosts: localhost
  connection: local
  tasks:
    - name: Check if VAL is greater than 10
      when: VAL | int > 10
      ansible.builtin.debug:
        msg: "{{ VAL }} is greater than 10"