- name: check for the global variable
  hosts: all
  connection: local
  vars:
    name: "don"
  tasks:
    - name: name of the variable
      vars:
        magic: "donotmagic"
      ansible.builtin.debug:
        msg: the magic is {{ magic }}  
    - name: name of the global variable
      ansible.builtin.debug:
        msg: the magic is {{ name }}  
           