- name: learning variables
  hosts: localhost
  connection: local
  tasks:
    - name: print the variables
      vars:
        url = "kishore"
      ansible.builtin.debug:
        msg: the varible value is {{url}}  