 - name: vault
   hosts: localhost
   connection: local
   tasks:
    - name: Download Vault repo file
      ansible.builtin.get_url:
      url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      dest: /etc/yum.repos.d/hashicorp.repo
    - name: install the vault
      ansible.builtin.dnf:
        name: nginx
        state: installed  
